server:
  port: 8080

# TOP LEVEL - No indentation
google:
  client:
    id: ${GOOGLE_CLIENT_ID:969553684702-9knn36242qfblc6b44jctm609j15scva.apps.googleusercontent.com}

spring:
  application:
    name: event-booking-superapp
  config:
    import: optional:file:.env[.properties]

  # PostgreSQL
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Google OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile